# Generated by Django 5.1.2 on 2024-11-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expected_response',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Response'),
        ),
    ]
