# Generated by Django 5.1.2 on 2024-11-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_expected_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_response_duration', models.DateTimeField(blank=True, null=True, verbose_name='Expected Response Durations')),
            ],
        ),
    ]
