# Generated by Django 5.1.2 on 2024-11-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticketsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketsettings',
            options={'verbose_name': 'Ticket Setting', 'verbose_name_plural': 'Ticket Settings'},
        ),
        migrations.AlterField(
            model_name='ticketsettings',
            name='expected_response_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Expected Response Duration'),
        ),
    ]
